DROP TABLE IF EXISTS Customer;

DROP TABLE IF EXISTS SMS_RECORD;
  
CREATE TABLE Customer (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  plan VARCHAR(100) NOT NULL
);


  
CREATE TABLE SMS_RECORD  (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  cust_id INT NOT NULL,
  sms_count INT NOT NULL,
  month_year VARCHAR(255) NOT NULL
);

